config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  
  get "/about" => 'homes#about'
  get "/demo" => 'homes#demo'
  
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  def top
  end

  def about
  end

  def demo
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
about 

<%=link_to "admin", new_admin_registration_path %>

<% if user_signed_in? %>
    ユーザーでログインしています
    <%=link_to "ユーザーログアウト",  destroy_user_session_path, method: :delete %>
<% end %>

<% if admin_signed_in? %>
    管理者でログインしています
    <%=link_to "管理者ログアウト",  destroy_admin_session_path, method: :delete %>
<% end %>

app/views/homes/demo.html.erb
OKdesu

<% if user_signed_in? %>
    ユーザーでログインしています
    <%=link_to "ユーザーログアウト",  destroy_user_session_path, method: :delete %>
<% end %>

<% if admin_signed_in? %>
    管理者でログインしています
    <%=link_to "管理者ログアウト",  destroy_admin_session_path, method: :delete %>
<% end %>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

<div class="a">
    <div class="b">1<br>1<br>1</div>
    <div class="b">2<br>1<br>1</div>
    <div class="b">3<br>1<br>1</div>
</div>

<div id="wrapper">
    <div id="contents">
      あいうえお<br>
      かきくけこ<br>
      さしすせそ<br>
      たちつてと<br>
      なにぬねの<br>
      はひふへほ<br>
      まみむめも<br>
      や　ゆ　よ<br>
      らりるれろ<br>
      わ　　　を<br>
      ん
    </div>
</div>


<% if user_signed_in? %>
    ユーザーでログインしています
    <%=link_to "ユーザーログアウト",  destroy_user_session_path, method: :delete %>
<% end %>

<% if admin_signed_in? %>
    管理者でログインしています
    <%=link_to "管理者ログアウト",  destroy_admin_session_path, method: :delete %>
<% end %>

<%=link_to "user", new_user_registration_path %>